import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>E-commerce-store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div>
          <img
            src="https://images.pexels.com/photos/230544/pexels-photo-230544.jpeg?auto=compress&cs=tinysrgb&w=600"
            alt="dh"
            className="w-full"
          />
        </div>
      </div>
    </>
  );
}
